#pragma once

#define DISPLAY_WIDTH 640
#define DISPLAY_HEIGHT 360
#define FULLSCREEN true

#define CAMERA_WORLD_WIDTH DISPLAY_WIDTH
#define CAMERA_WORLD_HEIGHT DISPLAY_HEIGHT
#define CAMERA_WORLD_WIDTH_MAX (static_cast<float>(CAMERA_WORLD_WIDTH) / 2)
#define CAMERA_WORLD_HEIGHT_MAX (static_cast<float>(CAMERA_WORLD_HEIGHT) / 2)

#define DEFAULT_MONITOR_REFRESH_RATE 144
#define DEBUG_MONITOR_REFRESH_RATE 60

#define HIDE_CURSOR 1

#define OPEN_GL 1
#define RENDER_API OPEN_GL