#pragma once

#if DEBUG
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
// #define DISPLAY_WIDTH 640
// #define DISPLAY_HEIGHT 360
#else
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
#endif
#define FIT_TO_SCREEN 1
#define DEFAULT_MONITOR_REFRESH_RATE 144
#define DEBUG_MONITOR_REFRESH_RATE 120
